name: Functional tests
on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  test_list:
    name: Generate Tasklist
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.testGen.outputs.tests }}
    steps:
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install jq -y
      
      - name: Clone repository
        uses: actions/checkout@v2
      - id: testGen
        shell: bash
        run: |
          echo -n "::set-output name=tests::"
          for test in $(find tests/functional -name 'test*.js' | sort); do
            printf '{"name": "%s", "path": "%s"}' $(basename ${test%.js} | sed -n 's/test//p') $test
          done | jq -s -c
      - name: Check Tests
        shell: bash
        env:
          TEST_LIST: ${{ steps.testGen.outputs.tests }}
        run: |
          echo $TEST_LIST | jq
  build_test_app:
    name: Build Test Client
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false # Don't cancel other jobs
      matrix:
        version: ["5.15.2","6.2.1"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: build/
          key: ${{ github.sha }}-${{matrix.version}}

      - name: Install Linux packages
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install git libgl-dev libegl-dev libpolkit-gobject-1-dev clang-10 liboath-dev python3 -y
          python3 -m pip install aqtinstall
          aqt install-qt --outputdir /opt linux desktop ${{matrix.version}} gcc_64 -m all
      - name: Compile test client
        shell: bash
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          export PATH=/opt/${{matrix.version}}/gcc_64/bin:$PATH
          pip3 install -r requirements.txt
          git submodule update --remote --depth 1 i18n
          python3 scripts/importLanguages.py
          python3 scripts/generate_glean.py
          # Delete unit tests, so we can get to testing faster
          sed -i '/tests\/unit/d' mozillavpn.pro
          qmake CONFIG+=DUMMY QMAKE_CXX=clang++ QMAKE_LINK=clang++ CONFIG+=debug CONFIG+=inspector QT+=svg
          make -j$(nproc)
          mkdir build/
          cp ./src/mozillavpn build/
      - name: Check build
        run: |
          ls -ial build/
  functionaltests:
    name: Test ${{matrix.test.name}} on Qt-${{matrix.version }}
    needs: 
      - build_test_app
      - test_list
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    strategy:
      fail-fast: false # Don't cancel other jobs if a test fails
      matrix:
        test: ${{ fromJson(needs.test_list.outputs.matrix) }}
        version: ["5.15.2","6.2.1"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: build/
          key: ${{ github.sha }}-${{matrix.version}}

      - name: Install dependecies
        run: |
          sudo apt update
          sudo apt install git libgl-dev libegl-dev libpolkit-gobject-1-dev clang-10 liboath-dev python3 -y
          python3 -m pip install aqtinstall
          aqt install-qt --outputdir /opt linux desktop ${{matrix.version}} gcc_64 -m all
          sudo apt install --no-upgrade firefox xvfb -y
          pip3 install -r requirements.txt
          npm install
      
      - name: Check build
        shell: bash
        run: ./build/mozillavpn -v

      - name: Launching API proxy
        shell: bash
        run: ./tests/proxy/wsgi.py --mock-devices > /dev/null &

      - name: Running ${{matrix.test.name}} Tests
        id: runTests
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            export PATH=$GECKOWEBDRIVER:$(npm bin):$PATH
            export HEADLESS=yes
            mkdir -p $ARTIFACT_DIR
            xvfb-run -a npm run functionalTest -- ${{matrix.test.path}}
          on_retry_command: npm run cleanup-flaky-script-output
        env:
          ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
          ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
          ARTIFACT_DIR: ${{ runner.temp }}/artifacts
          MVPN_API_BASE_URL: http://localhost:5000
          MVPN_BIN: ./build/mozillavpn

      - name: Uploading artifacts
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: ${{matrix.test.name}} Logs
          path: ${{ runner.temp }}/artifacts